In [1]:
# Import the NumPy library with the alias 'np' for use in all problems
import numpy as np

In [2]:
# Week 2 Assignment 2.2: NumPy Assignment

In [3]:
# Problem 1: Create a NumPy array of integers from 1 to 10 using arange
array = np.arange(1, 11)
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
# Problem 2: Reshape the array into a 2x5 matrix
matrix = array.reshape(2, 5)
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [5]:
# Problem 3: Square each element of the original array
squared_array = np.square(array)
print(squared_array)

[  1   4   9  16  25  36  49  64  81 100]


In [6]:
# Problem 4: Calculate the mean, median, and standard deviation of the array
mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)
print(f"Mean: {mean}, Median: {median}, Standard Deviation: {std_dev}")

Mean: 5.5, Median: 5.5, Standard Deviation: 2.8722813232690143


In [7]:
# Problem 5: Create an array with NaN values, calculate mean of non-NaN values, and replace NaN with that mean
array_with_nan = np.array([1, 2, np.nan, 4, 5, np.nan, 7, 8], dtype=float)
mean_non_nan = np.nanmean(array_with_nan)
array_filled = np.where(np.isnan(array_with_nan), mean_non_nan, array_with_nan)
print(array_filled)

[1.  2.  4.5 4.  5.  4.5 7.  8. ]


In [8]:
# Problem 6: Extract the second row of the 2x5 matrix using indexing
second_row = matrix[1, :]
print(second_row)

[ 6  7  8  9 10]


In [9]:
# Problem 7: Use boolean indexing to find elements greater than 5 in the original array
greater_than_five = array[array > 5]
print(greater_than_five)

[ 6  7  8  9 10]


In [10]:
# Problem 8: Create an array of dates and calculate the difference in days between consecutive dates
dates = np.array(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04', '2025-01-05'], dtype='datetime64')
diff = np.diff(dates).astype('timedelta64[D]')
print(diff)

[1 1 1 1]
